### PR TITLE
Upgrading embedded PHP key

### PR DESCRIPTION
**Pull request by vilda-r7**

### CODE REVIEW

**Comment by vilda-r7** [comment]
Can you have a look @gearoidof ?

**Comment by gearoidof-r7** [comment]
+1

**Comment by nvtkaszpir** [comment]
Title should say 'GPG', not 'PHP' :D

**Comment by vilda** [comment]
Yeah, it's produced by gpg, it will be used by gpg, but gpg --export --armor exports PHP key :)

**Comment by nvtkaszpir** [comment]
ok, then P**G**P, not P**H**P
:)

**Pull request merged**
